[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:uvicorn]
command=uvicorn main:app --host 127.0.0.1 --port 8000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/uvicorn.log
stderr_logfile=/var/log/uvicorn.err

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx.log
stderr_logfile=/var/log/nginx.err